# Generated by Django 5.1 on 2024-10-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_recruiterprofilemodel_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='skill',
            new_name='skills',
        ),
        migrations.RemoveField(
            model_name='recruiterprofilemodel',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='recruiterprofilemodel',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='seekerprofilemodel',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='seekerprofilemodel',
            name='contact_no',
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='vacancy',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
