# Generated by Django 5.1 on 2024-10-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_jobapplymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofilemodel',
            name='skills',
            field=models.CharField(choices=[('programming', 'Programming'), ('networking', 'Networking'), ('graphics_design', 'Graphics Design'), ('cyber_security', 'Cyber Security')], max_length=100, null=True),
        ),
    ]
