# Generated by Django 5.1.2 on 2024-10-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_alter_jobmodel_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofilemodel',
            name='skills',
            field=models.CharField(choices=[('programming', 'Programming'), ('networking', 'Networking'), ('graphics_design', 'Graphics Design'), ('cyber_security', 'Cyber Security'), ('python', 'Python')], max_length=100, null=True),
        ),
    ]
