# Generated by Django 5.1.2 on 2024-10-28 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_recruiterprofilemodel_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplymodel',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_applications_as_job', to='myApp.jobmodel'),
        ),
        migrations.AlterField(
            model_name='jobapplymodel',
            name='job_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_applications_as_title', to='myApp.jobmodel'),
        ),
    ]
