# Generated by Django 5.1.2 on 2024-10-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_jobapplymodel_job_alter_jobapplymodel_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofilemodel',
            name='Profile_Pic',
            field=models.ImageField(null=True, upload_to='Media/Profile_Pic'),
        ),
        migrations.AddField(
            model_name='seekerprofilemodel',
            name='Profile_Pic',
            field=models.ImageField(null=True, upload_to='Media/Profile_Pic'),
        ),
    ]
